### ISSUE TITLE
SQL注入漏洞

### ISSUE THREAD

**Issue by lw-tech-soft** [Special-Week/nonebot_plugin_setu4#1]
get_data.py line:36 使用了不加以控制的用户输入keyword

使用例：```setu banana' or pid=xxxxx or title like 'banana```
可以做到从数据库中调取指定的pid

**Comment by Well2333** [comment]
已解决，目前用户输入的半角单引号 ( ' ) 会被替换为全角单引号 ( ‘ )，注入的sql语句无法闭合
