### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 1409109991** [Special-Week/nonebot_plugin_setu4#11]
把R18涩图的撤回CD单独弄出来，我想在群里开R18模式了(滑稽)

**Comment by Special-Week** [comment]
在init.py里面自动撤回部分可以加一个if r18判断
![image](https://user-images.githubusercontent.com/87489040/177940295-76b00eb2-9b10-4ede-9658-8388e5fbf2da.png)

**Comment by Special-Week** [comment]
每个人想要的功能细节可能都不一样, 可以按照自己喜好任意修改, 写了很多注释可以自己理解一下, 我这里就先close了
