### ISSUE TITLE
HTTP响应时间是不是设错了

### ISSUE THREAD

**Issue by wu5288540** [Special-Week/nonebot_plugin_setu4#14]
我用setu-now可以从Pixiv.re下图，但用setu4的时候就秒跳http连接超时，返回错误码408
另外superuser的设置是和setu-now一样吗，我使用添加白名单等指令的时候机器人全部识别为setu指令了

**Comment by Special-Week** [comment]
群里老哥都测过了, 今天i.pixiv.re抽风了访问失败或者返还状态码520, setu-now也一样
![0QMMJ7 _CQ@SC77_TE2 $0Q](https://user-images.githubusercontent.com/87489040/179345654-58c94455-0712-4c2e-a9ff-c14778734f64.png)
等图片代理站恢复正常吧

**Comment by Special-Week** [comment]
漏看第二段话了, 这两个插件指令太像了容易造成冲突, 建议这两个setu插件只载入一个

**Comment by Special-Week** [comment]
另外这个http访问超时是误报, 实际上是get抛出的异常
