### ISSUE TITLE
setu_perm_cfg.json 读取失败, 尝试重建 Expected object or value

### ISSUE THREAD

**Issue by chenyue314** [Special-Week/nonebot_plugin_setu4#15]
[WARNING] nonebot_plugin_setu4 | setu_perm_cfg.json 读取失败, 尝试重建
Expected object or value

出现这个错误 setu_perm_cfg.json文件就被重置空白了

**Comment by Special-Week** [comment]
> [WARNING] nonebot_plugin_setu4 | setu_perm_cfg.json 读取失败, 尝试重建 Expected object or value
> 
> 出现这个错误 setu_perm_cfg.json文件就被重置空白了

这个warning是在插件读不到配置的时候跑出异常并生成空白的配置文件的，一般在第一次运行的时候触发，如果是正常使用多次触发了，能否提供一下出发条件以及日志？

**Comment by chenyue314** [comment]
> 

就是启动nonebot时候出现，它重写之后就触发了，主要是因为这个问题，就没法设置单个群的权限

**Comment by chenyue314** [comment]
> > [WARNING] nonebot_plugin_setu4 | setu_perm_cfg.json 读取失败, 尝试重建 Expected object or value
> > 出现这个错误 setu_perm_cfg.json文件就被重置空白了
> 
> 这个warning是在插件读不到配置的时候抛出异常并生成空白的配置文件的，一般在第一次运行的时候触发，如果是正常使用多次触发了，能否提供一下出发条件以及日志？

不编辑文件内容不会触发，编辑后就会触发。不编辑文件里面就只有括号 {}，如果编辑了一点都会触发重写

**Comment by Special-Week** [comment]
> > > [WARNING] nonebot_plugin_setu4 | setu_perm_cfg.json 读取失败, 尝试重建 Expected object or value
> > > 出现这个错误 setu_perm_cfg.json文件就被重置空白了
> > 
> > 
> > 这个warning是在插件读不到配置的时候抛出异常并生成空白的配置文件的，一般在第一次运行的时候触发，如果是正常使用多次触发了，能否提供一下出发条件以及日志？
> 
> 不编辑文件内容不会触发，编辑后就会触发。不编辑文件里面就只有括号 {}，如果编辑了一点都会触发重写

那么你手动修改后的文档符合json规范吗？另外设置单个群权限可以阅读readme，有指令进行权限管理，如果在某群用管理的命令，则会自动读取群号，如何和bot私聊使用管理指令，他会叫你输入id

**Comment by chenyue314** [comment]
> 

好像有点理解你的意思，就是 setu_perm_cfg.json里面的内容是要通过权限管理添加的是吧，
比如setu_wl add  添加会话至白名单
setu_wl del  移出会话自白名单之类的
但我发送触发还是触发setu发图的
“Error:图库中没有搜到关于_r18 on的图。”

是不是我不是管理员权限才这样，setu4的superuser读取.env的吗，还是要另外设置这样

我的. env 里面的格式是这样 SUPERUSER=["qq号] #配置机器人超级用户

我想是不是在这里面出问题

**Comment by Special-Week** [comment]
> > 
> 
> 好像有点理解你的意思，就是 setu_perm_cfg.json里面的内容是要通过权限管理添加的是吧， 比如setu_wl add 添加会话至白名单 setu_wl del 移出会话自白名单之类的 但我发送触发还是触发setu发图的 “Error:图库中没有搜到关于_r18 on的图。”
> 
> 是不是我不是管理员权限才这样，setu4的superuser读取.env的吗，还是要另外设置这样
> 
> 我的. env 里面的格式是这样 SUPERUSER=["qq号] #配置机器人超级用户
> 
> 我想是不是在这里面出问题

权限管理需要发送者是bot的superuser，也就是.env里面设置的SUPERUSER

**Comment by chenyue314** [comment]
> > > 
> > 
> > 
> > 好像有点理解你的意思，就是 setu_perm_cfg.json里面的内容是要通过权限管理添加的是吧， 比如setu_wl add 添加会话至白名单 setu_wl del 移出会话自白名单之类的 但我发送触发还是触发setu发图的 “Error:图库中没有搜到关于_r18 on的图。”
> > 是不是我不是管理员权限才这样，setu4的superuser读取.env的吗，还是要另外设置这样
> > 我的. env 里面的格式是这样 SUPERUSER=["qq号] #配置机器人超级用户
> > 我想是不是在这里面出问题
> 
> 权限管理需要发送者是bot的superuser，也就是.env里面设置的SUPERUSER

搞明白了，感谢。
如果nonebot命令头默认是“/”的话，权限管理得加“/”才能触发，不然触发是插件获取图片的命令

**Comment by Special-Week** [comment]
> > > > 
> > > 
> > > 
> > > 好像有点理解你的意思，就是 setu_perm_cfg.json里面的内容是要通过权限管理添加的是吧， 比如setu_wl add 添加会话至白名单 setu_wl del 移出会话自白名单之类的 但我发送触发还是触发setu发图的 “Error:图库中没有搜到关于_r18 on的图。”
> > > 是不是我不是管理员权限才这样，setu4的superuser读取.env的吗，还是要另外设置这样
> > > 我的. env 里面的格式是这样 SUPERUSER=["qq号] #配置机器人超级用户
> > > 我想是不是在这里面出问题
> > 
> > 
> > 权限管理需要发送者是bot的superuser，也就是.env里面设置的SUPERUSER
> 
> 搞明白了，感谢。 如果nonebot命令头默认是“/”的话，权限管理得加“/”才能触发，不然触发是插件获取图片的命令

权限管理的优先级是比setu高的，如果你是superuser，使用了权限管理的指令就会触发权限管理，并且事件向下阻断，如果不是superuser，使用了权限管理命令，必然匹配不到管理指令，只能向下匹配到了setu命令，并且事件也向下阻断了
