### ISSUE TITLE
如何同时搜索多个tag

### ISSUE THREAD

**Issue by if-u-can** [Special-Week/nonebot_plugin_setu4#17]
是需要配置吗

**Comment by Special-Week** [comment]
暂时没实现多tag搜索

**Comment by wu5288540** [comment]
确定不加入多tag功能吗
（试着自己改了但是水平不足没实现）

**Comment by wu5288540** [comment]
> 暂时没实现多tag搜索

确定不加入多tag功能吗，API那边好像是支持用[]string的形式实现多重tag的（试着自己改了但是学过的代码已经差不多还回去了水平不足没实现）

**Comment by Special-Week** [comment]
> > 暂时没实现多tag搜索
> 
> 确定不加入多tag功能吗，API那边好像是支持用[]string的形式实现多重tag的（试着自己改了但是学过的代码已经差不多还回去了水平不足没实现）

有空一定

**Comment by Special-Week** [comment]
加了

**Comment by wu5288540** [comment]
> 加了

好耶\(^o^)/~
