### ISSUE TITLE
关于代理问题

### ISSUE THREAD

**Issue by ShanShuWu** [Special-Week/nonebot_plugin_setu4#18]
您好，我是一个新手，在使用插件并使用setu命令拉取图片时，出现408错误，后台显示http访问超时，然后我使用v2rayn尝试（全局模式）但是仍然是http访问超时，请问我该如何操作？

**Comment by Special-Week** [comment]
你先不使用代理, 访问一下https://pixiv.re试试看能不能正常访问

**Comment by ShanShuWu** [comment]
可以，就是有点慢

**Comment by ShanShuWu** [comment]
每次都是http超时

**Comment by Special-Week** [comment]
https://i.pixiv.re/img-original/img/2020/12/16/17/59/41/86335792_p0.jpg
https://i.pixiv.re/img-original/img/2021/07/22/21/21/02/91422487_p0.jpg
我从数据库拿出了两个链接, 你用浏览器试试看能不能正常访问到图片

**Comment by ShanShuWu** [comment]
第一张加载到耳朵就不动了，第二张图片加载了一会加载出来了，第二张速度还算可以

**Comment by ShanShuWu** [comment]
第一张超时了一下

**Comment by Special-Week** [comment]
> 第一张加载到耳朵就不动了，第二张图片加载了一会加载出来了，第二张速度还算可以

我感觉也许是你网络的原因, 按道理pixiv.re在大陆可以直接访问(也许看地区?), 你换个网络试试看

**Comment by ShanShuWu** [comment]
机器人是在租赁的服务器上运行的，或许我该试试代理啥的？

**Comment by Special-Week** [comment]
那你在你的服务器上试试看能不能访问这个链接
http访问超时的报错原因是: 通过链接get图片的时候长时间未响应抛出异常, 输出在控制台并且返还408

**Comment by ShanShuWu** [comment]
我使用了代理，浏览器能很快并正常访问，但是仍然无法用机器人拉取图片，是有什么代理的设置项吗

**Comment by Special-Week** [comment]
> 我使用了代理，浏览器能很快并正常访问，但是仍然无法用机器人拉取图片，是有什么代理的设置项吗

代码是不能直接调用你那个代理的, 你开了全局模式可能直接报错, 调用你这个代理需要一定程度上改一下源码中的DownloadPic那个函数

**Comment by ShanShuWu** [comment]
好的，谢谢大佬，很感谢你能耐心回答我的问题

**Comment by ShanShuWu** [comment]
刚刚突然成功了，然后就成功了一次，后面又不行了哈哈哈

**Comment by ShanShuWu** [comment]
想咨询一下，阿里云tx云之类的机器能用这个反向代理吗（doge

**Comment by Special-Week** [comment]
> 



> 想咨询一下，阿里云tx云之类的机器能用这个反向代理吗（doge

我自己的服务器是tx和百度的, 没遇到这个问题

**Comment by ShanShuWu** [comment]
好的，十分感谢

**Comment by ShanShuWu** [comment]
我换了个腾讯云的服务器（喜），可以正常获取图片，但是没法发送出去（悲），网上搜索没有找到满意的解决方法，这是我机器的问题吗
![L4C7EU9F3LG4TV42`QIP5Y](https://user-images.githubusercontent.com/112482297/189099400-48455b26-8202-450d-87a0-d0e7cac2a1a6.jpg)

**Comment by Special-Week** [comment]
> 我换了个腾讯云的服务器（喜），可以正常获取图片，但是没法发送出去（悲），网上搜索没有找到满意的解决方法，这是我机器的问题吗 ![L4C7EU9F3LG4TV42`QIP5Y](https://user-images.githubusercontent.com/112482297/189099400-48455b26-8202-450d-87a0-d0e7cac2a1a6.jpg)

能否提供一下你的运行环境, gocq版本, nonebot版本, 以及你有无修改过代码

**Comment by ShanShuWu** [comment]
我足的服务器硬盘比较小，所以用的windows server2012 r2,gocqhttp是v1.0.0-rc3  windowsamd64,nonebot是 nonebot cli version 0.6.7

**Comment by Special-Week** [comment]
> 我足的服务器硬盘比较小，所以用的windows server2012 r2,gocqhttp是v1.0.0-rc3 windowsamd64,nonebot是 nonebot cli version 0.6.7

好像是我这边的原因, 我把之前测试的代码不小心提交上pypi上去了, 我重新传一份

**Comment by Special-Week** [comment]
> 我足的服务器硬盘比较小，所以用的windows server2012 r2,gocqhttp是v1.0.0-rc3 windowsamd64,nonebot是 nonebot cli version 0.6.7

我重新上传了pypi, 国内源可能过几分钟才能下载得到, 最新的版本号是0.0.18

**Comment by CaptBK13** [comment]
我之前也出现一样的问题，经过和404佬的交流，把setu的cd不要设置为0就没再出过问题了，另外我还加长了下载图片的timeout响应时间，原本是60，我目前版本是nonebot_plugin_setu4-0.0.16，如果你0.0.18还这个问题可以参考下
我是阿里云服务器，没用代理，

**Comment by ShanShuWu** [comment]
感谢大佬们帮忙，昨天已经解决了，更新后没有问题了（昨天没评论上），现在是用的阿里云服务器，代理没有出现问题，现在可以很好地运行插件 @CaptBK13 @Special-Week
