### ISSUE TITLE
群聊如何开启，不太清楚白名单管理指令在哪里使用？

### ISSUE THREAD

**Issue by cy920820** [Special-Week/nonebot_plugin_setu4#21]

**Comment by Special-Week** [comment]
使用superuser对机器人发送相关指令(群聊私聊都行), 例如 "setu_wl add", 机器人会找你要添加的对象, 具体阅读readme

**Comment by cy920820** [comment]
superuser 在哪里设置

**Comment by Special-Week** [comment]
> superuser 在哪里设置

这是你机器人.env的基本配置, 机器人的超级用户

**Comment by cy920820** [comment]
设置超管了，但是仍然没办法对话
![image](https://user-images.githubusercontent.com/21211512/193010440-4f4fe5a6-79a0-4c0e-b351-4e0fcd59289c.png)

本地环境配置
![image](https://user-images.githubusercontent.com/21211512/193010508-fdd29080-3447-48de-a058-559ac2975525.png)

**Comment by Special-Week** [comment]
> 设置超管了，但是仍然没办法对话 ![image](https://user-images.githubusercontent.com/21211512/193010440-4f4fe5a6-79a0-4c0e-b351-4e0fcd59289c.png)
> 
> 本地环境配置 ![image](https://user-images.githubusercontent.com/21211512/193010508-fdd29080-3447-48de-a058-559ac2975525.png)

你既然第一行已经设置了你的env指向dev, 那你应该去.env.dev去设置超级用户

**Comment by cy920820** [comment]
还是不行啊 
![image](https://user-images.githubusercontent.com/21211512/193012126-38d0245b-1752-4728-bee0-10cd10ea49de.png)

**Comment by Special-Week** [comment]
使用你的superuser发送指令

**Comment by cy920820** [comment]
> 使用你的superuser发送指令

用的就是 673308817 这个supersuer 发送的，还是回复刚刚截图的

**Comment by Special-Week** [comment]
> > 使用你的superuser发送指令
> 
> 用的就是 673308817 这个supersuer 发送的，还是回复刚刚截图的

如果出现的是上图的情况, 那么说明指令肯定不是nonebot的superuser发出的消息, 因为权限管理一系列的响应器的参数permission=SUPERUSER, 而且权限管理部分的响应器优先级比setu响应器高且block=True.

**Comment by Special-Week** [comment]
> > 使用你的superuser发送指令
> 
> 用的就是 673308817 这个supersuer 发送的，还是回复刚刚截图的

还有一种可能, 你env没有设置command_start, 导致所有command响应器需要"/"作为起始符

**Comment by cy920820** [comment]
> > > 使用你的superuser发送指令
> > 
> > 
> > 用的就是 673308817 这个supersuer 发送的，还是回复刚刚截图的
> 
> 还有一种可能, 你env没有设置command_start, 导致所有command响应器需要"/"作为起始符. nonebot源码config.py内默认command_start: Set[str] = {"/"}

那我应该将起始符设置成什么呢？

**Comment by Special-Week** [comment]
> > > > 使用你的superuser发送指令
> > > 
> > > 
> > > 用的就是 673308817 这个supersuer 发送的，还是回复刚刚截图的
> > 
> > 
> > 还有一种可能, 你env没有设置command_start, 导致所有command响应器需要"/"作为起始符. nonebot源码config.py内默认command_start: Set[str] = {"/"}
> 
> 那我应该将起始符设置成什么呢？

https://v2.nonebot.dev/docs/api/config#Config-command_start

**Comment by cy920820** [comment]
> > > > > 使用你的superuser发送指令
> > > > 
> > > > 
> > > > 用的就是 673308817 这个supersuer 发送的，还是回复刚刚截图的
> > > 
> > > 
> > > 还有一种可能, 你env没有设置command_start, 导致所有command响应器需要"/"作为起始符. nonebot源码config.py内默认command_start: Set[str] = {"/"}
> > 
> > 
> > 那我应该将起始符设置成什么呢？
> 
> https://v2.nonebot.dev/docs/api/config#Config-command_start

我的意思是值应该设置成什么字符串呢？

**Comment by Special-Week** [comment]
设置成什么东西看你自己喜好, 你自己nonebot配置的command_start自己去看nonebot那边, 我这里只是一个插件. 你不应该在这里提问的
