### ISSUE TITLE
关于此插件报 PIL.UnidentifiedImageError 错误。(无法识别图像文件)

### ISSUE THREAD

**Issue by Voice-of-Shadow** [Special-Week/nonebot_plugin_setu4#23]
插件通过PIL读取内存中的图片错误。可能是下载获取的图片错误。pixiv.re 可 ping 通。已配置setu_save。

报错截图如下：
![QQ截图20221015065810](https://user-images.githubusercontent.com/115323324/195956316-023acfeb-6afc-46e1-a152-61aa4b5075f6.png)

**Comment by Special-Week** [comment]
pixiv.re返回的图片是空白，从昨天下午开始这样的，只能暂时先等待

**Comment by Voice-of-Shadow** [comment]
emmm、原来是pixiv.re抽风。这边以为是魔法的问题于是重新配了、curl 获取得到图。不知何时能好、

然后关于readme.md的小反馈：
env配置项表格中。setu_regex 的示例(example) 为 "setu_save = see description"。

**Comment by forchannot** [comment]
原来如此，我说怎么最近不行了

**Comment by Special-Week** [comment]
重新构造了可用的图片url, 并且更新了数据库, 请从github下clone一下, pypi国内源也需要过几分钟才更新, 如果没问题的话请close

**Comment by Voice-of-Shadow** [comment]
测试已经可以正常使用。辛苦开发者维护~
