### ISSUE TITLE
关于目前更新使用的代理返回状态码 408

### ISSUE THREAD

**Issue by Voice-of-Shadow** [Special-Week/nonebot_plugin_setu4#26]
大概是下午的时候（
之前版本的.cat还是.re我似乎能用、(可能挂着魔法的缘故、但此插件似乎没要配置proxy)

作者看看这个代理、这个我暂时能用、
`setu_url = setu[5].replace('i.pixiv.re', 'px2.rainchan.win')`

**Comment by Special-Week** [comment]
我换了sex.nyan.xyz的

**Comment by Voice-of-Shadow** [comment]
sex.nyan.xyz 我报408了、超时似乎

**Comment by Special-Week** [comment]
好吧, 现在sex.nyan.xyz和i.pixiv.re出了一样的问题

**Comment by Special-Week** [comment]
我晚点在env设置一个代理变量吧

**Comment by Voice-of-Shadow** [comment]
作者后续优化可以吧"魔法阵"画进来、反代网站萌新又不太会搭建、而且感觉看上去好像挺容易炸的样子、、[捂脸]

**Comment by Special-Week** [comment]
翻了一下google找到了10个代理, 插件也给了代理切换的接口顺便带了一个ping测试连通性, 大概就这样了
