### ISSUE TITLE
无法适配nonebot版本rc1

### ISSUE THREAD

**Issue by zuixiaoxiao** [Special-Week/nonebot_plugin_setu4#27]
![image](https://user-images.githubusercontent.com/108536651/197815325-b4effb17-4c12-469d-b459-ec1f844102b0.png)
![image](https://user-images.githubusercontent.com/108536651/197815438-affb72c3-4c78-48d9-8623-356d8188d3a6.png)
请问可以适配吗

**Comment by Special-Week** [comment]
我早就适配了，你没更新。。。

**Comment by Special-Week** [comment]
我应该几天前就提交了适配，你有更新吗？

**Comment by zuixiaoxiao** [comment]
> 我应该几天前就提交了适配，你有更新吗？

emm刚更新，谢谢了
