### ISSUE TITLE
存了图 但存的不是很存

### ISSUE THREAD

**Issue by KANATA980122** [Special-Week/nonebot_plugin_setu4#29]
![image](https://user-images.githubusercontent.com/31950028/207263321-96a391f6-ffb4-4042-803c-a1aa68d9da13.png)
如图，path已经正确设置，然后涩涩完了之后是空的
![image](https://user-images.githubusercontent.com/31950028/207263757-64101610-bd88-4597-acbb-7f590418ccfe.png)

**Comment by Special-Week** [comment]
新建img文件夹

**Comment by Special-Week** [comment]
长时间没有回复, 我这里就block了, 你要把图片存到某个文件夹前提需要那个文件夹存在
