### ISSUE TITLE
关于apscheduler的版本适配

### ISSUE THREAD

**Issue by wu5288540** [Special-Week/nonebot_plugin_setu4#30]
由于nonebot2的更新，现在apscheduler的版本已经是0.2.0，许多插件也是依据这个版本做适配，但setu4会强制安装回旧版本导致在运行的时候出现
ImportError: cannot import name 'State' from 'nonebot.params' (/usr/local/lib/python3.10/site-packages/nonebot/params.py)

若使用旧版apscheduler会导致其他插件无法启动，若使用新版，这本插件无法导入，麻烦做一下调整适配

**Comment by Special-Week** [comment]
可我早就做了适配, 你没更新....

**Comment by wu5288540** [comment]
怪了，我今天又重装了，那我这报错哪来的，我先继续扫扫看，毕竟之前都能用

**Comment by wu5288540** [comment]
哦，我习惯性用nb入口安装和更新，内鬼是这边
用pip install --upgrade就正常了，还得是这边靠谱
