### ISSUE TITLE
add_r18指令无法执行

### ISSUE THREAD

**Issue by NathanSummer** [Special-Week/nonebot_plugin_setu4#31]
配置了超管，但使用add_r18指令后bot没有反应

**Comment by Special-Week** [comment]
command_start

**Comment by NathanSummer** [comment]
> command_start

我全局设置为空的也要加/嘛？

**Comment by Special-Week** [comment]
> > command_start
> 
> 我全局设置为空的也要加/嘛？

你用的是不是这个仓库的，这个这个仓库可没有什么add_r18指令

**Comment by NathanSummer** [comment]
> 你用的是不是这个仓库的，这个这个仓库可没有什么add_r18指令

哦哦发错地方了，我用的是青春版

**Comment by Special-Week** [comment]
> > 你用的是不是这个仓库的，这个这个仓库可没有什么add_r18指令
> 
> 哦哦发错地方了，我用的是青春版

那你env的command_start是什么，add_r18用的响应器是on_command，需要加上你env设置的命令头，如果env没有默认是/

**Comment by NathanSummer** [comment]
> 那你env的command_start是什么，add_r18用的响应器是on_command，需要加上你env设置的命令头，如果env没有默认是/

![image](https://user-images.githubusercontent.com/88868171/210317209-2855f4d2-da68-45cf-8e8f-5d5e45cb3d18.png)
这样的哦

**Comment by Special-Week** [comment]
> > 你用的是不是这个仓库的，这个这个仓库可没有什么add_r18指令
> 
> 哦哦发错地方了，我用的是青春版

而且命令后你还要加参数，也就是qq群或者qq号

**Comment by NathanSummer** [comment]
> 而且命令后你还要加参数，也就是qq群或者qq号

辣当然咯

**Comment by NathanSummer** [comment]
而且我设置了SUPERUSER的，但是我还是有CD

**Comment by Special-Week** [comment]
那我也不清楚你那边发生了什么
![Screenshot_2023-01-03-15-50-28-96_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/87489040/210317592-09a47db7-c60b-49d5-aa12-f6aa969079de.jpg)

**Comment by NathanSummer** [comment]
感觉好像是它没有读取到我的超管账号？

**Comment by Special-Week** [comment]
> 而且我设置了SUPERUSER的，但是我还是有CD

我觉得你大概率是superuser配置的问题

**Comment by Special-Week** [comment]
> 感觉好像是它没有读取到我的超管账号？


SUPERUSERS = ["xxxx","yyyy"]

**Comment by NathanSummer** [comment]
感谢！！！
