### ISSUE TITLE
要使用涩图帮助指令的时候会直接触发请求涩图

### ISSUE THREAD

**Issue by Alcohol233** [Special-Week/nonebot_plugin_setu4#33]
如题，当给装了插件的bot发送“色图帮助”时，会直接发“帮助”tag的涩图而不是出现帮助文档。

**Comment by Special-Week** [comment]
![image](https://github.com/Special-Week/nonebot_plugin_setu4/assets/87489040/243330d1-af11-48e5-9fd0-e9652ce3d284)

**Comment by Alcohol233** [comment]
>
