### ISSUE TITLE
OperationalError('no such column: False')

### ISSUE THREAD

**Issue by Proito666** [Special-Week/nonebot_plugin_setu4#36]
setu指令报错   OperationalError('no such column: False') 
权限管理相关指令正常， 通过nb安装和直接拉代码试了都不行。
后台也没有报错日志

**Comment by Proito666** [comment]
![Cache_70c9a1333eb96788](https://github.com/Special-Week/nonebot_plugin_setu4/assets/53973735/8dc6a573-abca-4812-a3ff-68e80251f7d0)
![Cache_-12ce59ac6eba4acd](https://github.com/Special-Week/nonebot_plugin_setu4/assets/53973735/31d3ac2e-ad43-4fcb-a3c2-c2a521fc13e1)

**Comment by Special-Week** [comment]
有拉取最新的数据库吗，也就是resource里面的lolicon.db，我有一次改过表结构

**Comment by Proito666** [comment]
我直接在github上拉了完整的代码，带lolicon.db也不行

**Comment by Special-Week** [comment]
你再确定一下你运行的bot是我用的这份代码，这个报错是说数据表没有叫False的字段，我搓sql的代码明明用的是r18字段

**Comment by Special-Week** [comment]
我自己刚刚测试了一下, 是正常工作的

**Comment by Proito666** [comment]
可能是我sqlite3的问题，我是后面装的这个

**Comment by Proito666** [comment]
解决了，应该是我sqlite3版本的问题，我把r18字段转成0和1就行了
