### ISSUE TITLE
要不把18的图单独文件夹存放吧

### ISSUE THREAD

**Issue by yangdffdzvzvr** [Special-Week/nonebot_plugin_setu4#38]
佬，要不把18的图单独文件夹存放吧，比如img/r8之类的，整理起来就方便了QAQ

**Comment by Special-Week** [comment]
我一直忘记了这条issue, 我已经把他加上去了, 按照填入的setu_save路径, 会在下面新建两个文件夹, nsfw(Not Safe For Work)和sfw, 前者代表r18
![image](https://github.com/Special-Week/nonebot_plugin_setu4/assets/87489040/be561e3d-c950-4e3e-948e-23de9a382865)
![image](https://github.com/Special-Week/nonebot_plugin_setu4/assets/87489040/8e7d33e4-ae84-48f9-a7fa-b0b4917c623a)
![image](https://github.com/Special-Week/nonebot_plugin_setu4/assets/87489040/18051d70-85ea-48d3-9d4a-37296c3c5a52)
