### ISSUE TITLE
触发命令的权限里没有superuser导致自己私聊的时候没有图

### ISSUE THREAD

**Issue by wu5288540** [Special-Week/nonebot_plugin_setu4#41]
由于发现谁都能要到图除了管理员自己私聊，因此看了下代码文件，发现_init_.py文件第34行是

 permission=PRIVATE_FRIEND | GROUP,

尝试改成

 permission=PRIVATE_FRIEND | GROUP | SUPERUSER,

暂时解决了这个奇妙的BUG
麻烦作者看看这个解决方法是否ok

**Comment by Special-Week** [comment]
问一下你是什么客户端，我这边shamrock和gocqhttp都没出现这个问题

**Comment by wu5288540** [comment]
> 问一下你是什么客户端，我这边shamrock和gocqhttp都没出现这个问题

我这边是用的gocqhttp的一个转接插件，接到个人bot上，查了nonebot日志，发现superuser私聊的时候没有识别到指令，matcher没有匹配到插件，被忽略跳过了，加指令头也没用。但发图之外的所有指令有效的，包括黑白名单操作和各种开关
不知道是不是我nonebot版本问题，有段时间没更新了，还是2.0rc2

**Comment by Special-Week** [comment]
我这边复现不来，我就直接把permission=PRIVATE_FRIEND | GROUP删了吧，我加这条目的是防止临时会话也被响应，导致容易封号，考虑到主流的客户端上报事件上就已经默认过滤临时会话，我直接删了好了
